In [2]:
import numpy as np

In [3]:
a1 = np.array([1, 2, 3])
a1

array([1, 2, 3])

In [5]:
a2 = np.array([[1, 7, 5],
              [3, 9, 4]])
a2

array([[1, 7, 5],
       [3, 9, 4]])

In [8]:
a3 = np.array([[[4, 6, 8],
               [3, 5, 7],
                [0, 1, 9]],
               [[2, 5, 9],
                [7, 6, 5],
                [5, 0, 3]]])
a3

array([[[4, 6, 8],
        [3, 5, 7],
        [0, 1, 9]],

       [[2, 5, 9],
        [7, 6, 5],
        [5, 0, 3]]])

In [10]:
a1.ndim, a1.shape, a1.dtype, a1.size

(1, (3,), dtype('int64'), 3)

In [11]:
a2.ndim, a2.shape, a2.dtype, a2.size

(2, (2, 3), dtype('int64'), 6)

In [12]:
a3.ndim, a3.shape, a3.dtype, a3.size

(3, (2, 3, 3), dtype('int64'), 18)

In [13]:
import pandas as pd

In [15]:
df = pd.DataFrame(a2)
df

0  1  2
0  1  7  5
1  3  9  4

In [17]:
ones = np.ones((10, 2))
ones

array([[1., 1.],
       [1., 1.],
       [1., 1.],
       [1., 1.],
       [1., 1.],
       [1., 1.],
       [1., 1.],
       [1., 1.],
       [1., 1.],
       [1., 1.]])

In [18]:
zeros = np.zeros((7, 2, 3))
zeros

array([[[0., 0., 0.],
        [0., 0., 0.]],

       [[0., 0., 0.],
        [0., 0., 0.]],

       [[0., 0., 0.],
        [0., 0., 0.]],

       [[0., 0., 0.],
        [0., 0., 0.]],

       [[0., 0., 0.],
        [0., 0., 0.]],

       [[0., 0., 0.],
        [0., 0., 0.]],

       [[0., 0., 0.],
        [0., 0., 0.]]])

In [19]:
range_array = np.arange(0, 100, 3)
range_array

array([ 0,  3,  6,  9, 12, 15, 18, 21, 24, 27, 30, 33, 36, 39, 42, 45, 48,
       51, 54, 57, 60, 63, 66, 69, 72, 75, 78, 81, 84, 87, 90, 93, 96, 99])

In [20]:
random_array = np.random.randint(0, 10, size=(3, 5))
random_array

array([[4, 1, 1, 6, 6],
       [6, 8, 1, 0, 4],
       [5, 5, 4, 8, 2]])

In [21]:
np.random.seed(42)

random_array_1 = np.random.randint(0, 10, size=(4, 6))
random_array_1

array([[6, 3, 7, 4, 6, 9],
       [2, 6, 7, 4, 3, 7],
       [7, 2, 5, 4, 1, 7],
       [5, 1, 4, 0, 9, 5]])

In [22]:
random_array_1

array([[6, 3, 7, 4, 6, 9],
       [2, 6, 7, 4, 3, 7],
       [7, 2, 5, 4, 1, 7],
       [5, 1, 4, 0, 9, 5]])

In [23]:
random_array_2 = np.random.randint(1, 10, size=(3, 7))
np.unique(random_array_2)

array([1, 2, 3, 4, 5, 7, 9])

In [25]:
random_array_2[0]

array([9, 1, 3, 7, 4, 9, 3])

In [26]:
random_array_1[0]

array([6, 3, 7, 4, 6, 9])

In [27]:
a1[0]

np.int64(1)

In [28]:
a3[0]

array([[4, 6, 8],
       [3, 5, 7],
       [0, 1, 9]])

In [29]:
a3[:,2,:]

array([[0, 1, 9],
       [5, 0, 3]])

In [30]:
a3[0, 1]

array([3, 5, 7])

In [31]:
a3

array([[[4, 6, 8],
        [3, 5, 7],
        [0, 1, 9]],

       [[2, 5, 9],
        [7, 6, 5],
        [5, 0, 3]]])

In [33]:
a3[0, [0, 1]]

array([[4, 6, 8],
       [3, 5, 7]])

In [35]:
random_array_4 = np.random.randint(0, 10, size=(3, 5))
ones = np.ones((3, 5))

In [36]:
random_array_4 + ones

array([[ 7.,  8.,  3.,  1.,  4.],
       [ 2.,  8.,  4.,  2.,  6.],
       [ 6., 10.,  4.,  6.,  2.]])

In [37]:
ones = np.ones((5, 3))

In [38]:
random_array_4

array([[6, 7, 2, 0, 3],
       [1, 7, 3, 1, 5],
       [5, 9, 3, 5, 1]])

In [39]:
ones

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

In [41]:
ones = ones.reshape(3, 5)

In [42]:
random_array_4 + ones

array([[ 7.,  8.,  3.,  1.,  4.],
       [ 2.,  8.,  4.,  2.,  6.],
       [ 6., 10.,  4.,  6.,  2.]])

In [43]:
random_array_4 - ones

array([[ 5.,  6.,  1., -1.,  2.],
       [ 0.,  6.,  2.,  0.,  4.],
       [ 4.,  8.,  2.,  4.,  0.]])

In [44]:
random_array_4 * ones

array([[6., 7., 2., 0., 3.],
       [1., 7., 3., 1., 5.],
       [5., 9., 3., 5., 1.]])

In [45]:
random_array_4 ** ones

array([[6., 7., 2., 0., 3.],
       [1., 7., 3., 1., 5.],
       [5., 9., 3., 5., 1.]])

In [46]:
random_array_4 ** 2

array([[36, 49,  4,  0,  9],
       [ 1, 49,  9,  1, 25],
       [25, 81,  9, 25,  1]])

In [47]:
np.square(random_array_4)

array([[36, 49,  4,  0,  9],
       [ 1, 49,  9,  1, 25],
       [25, 81,  9, 25,  1]])

In [48]:
np.mean(random_array_4)

np.float64(3.8666666666666667)

In [49]:
np.max(random_array_4)

np.int64(9)

In [50]:
np.var(random_array_4)

np.float64(6.648888888888889)

In [51]:
random_array_4.reshape(3, 5, 1)

array([[[6],
        [7],
        [2],
        [0],
        [3]],

       [[1],
        [7],
        [3],
        [1],
        [5]],

       [[5],
        [9],
        [3],
        [5],
        [1]]])

In [52]:
random_array_4.T

array([[6, 1, 5],
       [7, 7, 9],
       [2, 3, 3],
       [0, 1, 5],
       [3, 5, 1]])

In [55]:
np.random.seed(0)

random_array_5 = np.random.randint(0, 10, size=(4, 3))

In [56]:
np.random.seed(0)

random_array_6 = np.random.randint(0, 10, size=(4, 3))

In [57]:
random_array_7 = np.dot(random_array_5, random_array_6)

ValueError: shapes (4,3) and (4,3) not aligned: 3 (dim 1) != 4 (dim 0)

In [58]:
new_random_array_6 = random_array_6.reshape(3, 4)

In [60]:
random_array_7 = np.dot(random_array_5, new_random_array_6)
random_array_7

array([[31, 12, 36, 33],
       [82, 99, 93, 98],
       [54, 53, 38, 46],
       [81, 87, 75, 83]])

In [61]:
t_random_array_6 = random_array_6.T

In [62]:
random_array_8 = np.dot(random_array_5, t_random_array_6)
random_array_8

array([[ 34,  42,  21,  38],
       [ 42, 139,  62, 115],
       [ 21,  62,  38,  59],
       [ 38, 115,  59, 101]])

In [63]:
random_array_7 > random_array_8

array([[False, False,  True, False],
       [ True, False,  True, False],
       [ True, False, False, False],
       [ True, False,  True, False]])

In [64]:
random_array_7 >= random_array_8

array([[False, False,  True, False],
       [ True, False,  True, False],
       [ True, False,  True, False],
       [ True, False,  True, False]])

In [66]:
random_array_6 > 3

array([[ True, False, False],
       [False,  True,  True],
       [False,  True, False],
       [ True,  True,  True]])

In [67]:
random_array_7 == random_array_8

array([[False, False, False, False],
       [False, False, False, False],
       [False, False,  True, False],
       [False, False, False, False]])

In [68]:
np.argsort(random_array_6)

array([[1, 2, 0],
       [0, 1, 2],
       [2, 0, 1],
       [0, 2, 1]])

In [69]:
random_array_6

array([[5, 0, 3],
       [3, 7, 9],
       [3, 5, 2],
       [4, 7, 6]])

In [70]:
np.sort(random_array_6)

array([[0, 3, 5],
       [3, 7, 9],
       [2, 3, 5],
       [4, 6, 7]])

In [71]:
a2

array([[1, 7, 5],
       [3, 9, 4]])

In [72]:
np.argsort(a2)

array([[0, 2, 1],
       [0, 2, 1]])

In [73]:
a3

array([[[4, 6, 8],
        [3, 5, 7],
        [0, 1, 9]],

       [[2, 5, 9],
        [7, 6, 5],
        [5, 0, 3]]])

In [74]:
np.argsort(a3)

array([[[0, 1, 2],
        [0, 1, 2],
        [0, 1, 2]],

       [[0, 1, 2],
        [2, 1, 0],
        [1, 2, 0]]])

In [75]:
np.argsort([5, 0, 3])

array([1, 2, 0])

In [77]:
np.argmax(random_array_6, axis=1)

array([0, 2, 1, 1])

In [78]:
random_array_6

array([[5, 0, 3],
       [3, 7, 9],
       [3, 5, 2],
       [4, 7, 6]])

In [79]:
np.argmax(random_array_6, axis=0)

array([0, 1, 1])

In [81]:
np.argmin(random_array_6, axis=0)

array([1, 0, 2])

In [82]:
np.argmin(random_array_6, axis=1)

array([1, 0, 2, 0])

In [ ]:
range_array = np.arange(1, 10, 2)
range_array